CREATE TABLE work_shelves
(
    id         BIGINT    NOT NULL AUTO_INCREMENT,
    user_id    BIGINT    NOT NULL,
    work_id    BIGINT    NOT NULL,
    shelf      ENUM ('WANT_TO_READ', 'CURRENTLY_READING', 'READ', 'DID_NOT_FINISH'),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_work_shelves PRIMARY KEY (id),
    CONSTRAINT FK_work_shelves_work_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_work_shelves_user_id FOREIGN KEY (work_id) REFERENCES works (id) ON DELETE CASCADE ON UPDATE CASCADE
);